spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/star-wars-planets
    username: root
    password: docker

swapi:
  url:
    base: https://swapi.dev/api
    planets: ${swapi.url.base}/planets


